# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import crud_pb2 as crud__pb2


class MapStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Crud = channel.unary_unary(
        '/helloworld.Map/Crud',
        request_serializer=crud__pb2.CommandRequest.SerializeToString,
        response_deserializer=crud__pb2.CommandReply.FromString,
        )


class MapServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Crud(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Crud': grpc.unary_unary_rpc_method_handler(
          servicer.Crud,
          request_deserializer=crud__pb2.CommandRequest.FromString,
          response_serializer=crud__pb2.CommandReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Map', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
